Repository romka-best/mindfusion-ai-backend, pull requests merged in 2025-04, with the labels that each got.

#156 Added handling of runway aspect ratio error with human-readable message
  bot/handlers/ai/runway_handler.py
  bot/locales/en.py
  bot/locales/es.py
  bot/locales/hi.py
  bot/locales/ru.py
Labels: ✨ UX

#155 Added logging for silent network errors
  main.py
Labels: 🛠 refactoring

#126 release 1.20.9
  bot/config.py
  bot/database/models/common.py
  bot/database/models/user.py
  bot/handlers/ai/chat_gpt_handler.py
  bot/handlers/ai/claude_handler.py
  bot/handlers/ai/dalle_handler.py
  bot/handlers/ai/deep_seek_handler.py
  bot/handlers/ai/eightify_handler.py
  bot/handlers/ai/face_swap_handler.py
  bot/handlers/ai/flux_handler.py
  bot/handlers/ai/gemini_handler.py
  bot/handlers/ai/gemini_video_handler.py
  bot/handlers/ai/grok_handler.py
  bot/handlers/ai/kling_handler.py
  bot/handlers/ai/luma_handler.py
  bot/handlers/ai/midjourney_handler.py
  bot/handlers/ai/model_handler.py
  bot/handlers/ai/music_gen_handler.py
  bot/handlers/ai/perplexity_handler.py
  bot/handlers/ai/photoshop_ai_handler.py
  bot/handlers/ai/pika_handler.py
  bot/handlers/ai/recraft_handler.py
  bot/handlers/ai/runway_handler.py
  bot/handlers/ai/stable_diffusion_handler.py
  bot/handlers/ai/suno_handler.py
  bot/handlers/common/common_handler.py
  bot/handlers/payment/payment_handler.py
  bot/handlers/settings/settings_handler.py
  bot/helpers/checkers/check_unresolved_requests.py
  bot/helpers/handlers/handle_kling_webhook.py
  bot/helpers/handlers/handle_luma_webhook.py
  bot/helpers/handlers/handle_midjourney_webhook.py
  bot/helpers/handlers/handle_pika_webhook.py
  bot/helpers/handlers/handle_replicate_webhook.py
  bot/helpers/handlers/handle_stripe_webhook.py
  bot/helpers/handlers/handle_suno_webhook.py
  bot/helpers/handlers/handle_yookassa_webhook.py
  bot/helpers/senders/send_ai_message.py
  bot/helpers/updaters/update_daily_limits.py
  bot/integrations/runway.py
  bot/keyboards/ai/model.py
  bot/keyboards/settings/settings.py
  bot/locales/en.py
  bot/locales/es.py
  bot/locales/hi.py
  bot/locales/ru.py
  bot/locales/texts.py
  main.py
  requirements.txt
Labels: 🐞 bug

#158 release 1.20.10
  bot/database/models/common.py
  bot/handlers/ai/midjourney_handler.py
  bot/handlers/ai/model_handler.py
  bot/handlers/settings/settings_handler.py
  bot/helpers/handlers/handle_midjourney_webhook.py
  bot/integrations/midjourney.py
  bot/keyboards/settings/settings.py
  bot/locales/en.py
  bot/locales/es.py
  bot/locales/hi.py
  bot/locales/ru.py
  bot/locales/texts.py
  bot/utils/is_messages_limit_exceeded.py
Labels: 🚀 enhancement
